name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: astral-sh/setup-uv@v3
      - name: ruff
        run: |
          uv run ruff check
          uv run ruff format --check
      - name: mypy
        run: uv run mypy
      - name: pytest
        run: uv run pytest
